import Head from 'next/head'
import Header from '../components/Header'
import SendMail from '../components/SendMail'
import Login from '../components/login'
import Sidebar from '../components/Sidebar'
import Emails from './emails/emailList'
import { useDispatch, useSelector } from 'react-redux';
import { selectSendMessageIsOpen } from '../features/mailSlice'
import Image from 'next/image'
import styles from '../styles/Login.module.css'
import { useSession, signIn, signOut, getSession } from 'next-auth/react';


export default function Home() {
  const { data: session, status } = useSession()
  const sendMessageIsOpen = useSelector(selectSendMessageIsOpen)

  if (status === 'authenticated') {
    return (
      <div>
        <Head>
          <title>Daily Mail </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <header>
            <Header />
            {/* <Login /> */}
          </header>
          <section className='app-body'>
            <Sidebar />
            <Emails />
          </section>
          {sendMessageIsOpen && <SendMail />}
        </main>
      </div>
    )

  } else {
    return (
      <div className={styles.form}>
        <Image className={styles.img} src='/../public/assets/Asset.png' alt='image' width={'125'} height={'50'} />
        {/* <input className={styles.input} type="email" name='email' placeholder='Email' />
        <input className={styles.input} type="password" name="Password" id="" placeholder='Password' /> */}
        <p>You are not signed in</p>
        <button className={styles.button} onClick={() => signIn()}>Sign in</button>
      </div>
    )
  }
}
